// MPF show YAML generation.
//
// Two output dialects, because the format changed between MPF versions:
//
//   MPF 0.57+ (show_version 6) - the default.
//     Header must be exactly "#show_version=6"; MPF compares the first line for
//     string equality and raises AssertionError on a mismatch, so a 0.50-era
//     "#show_version=5" file will not load at all.
//     Steps carry an explicit "duration: 33ms". MPF parses a bare number as
//     SECONDS (Util.string_to_secs appends "s" when the string has no letters),
//     so "+1" means one second, not one frame. Spelling the milliseconds out
//     means the show runs at the right speed with the default speed: 1.
//
//   MPF 0.50-0.56 (show_version 5) - legacy.
//     "#show_version=5" and relative "time: '+1'" steps, matching what the
//     original tool produced. Only plays at the intended rate when the show is
//     started with speed set to the frame rate.
//
// Verified against mpf 0.80.x: assets/show.py, file_interfaces/yaml_interface.py,
// core/utility_functions.py and config_players/light_player.py.

import { projectDuration, frameCount } from './project.js';

export const MPF_TARGETS = {
  '0.80': { showVersion: 6, stepMode: 'duration', label: 'MPF 0.57 and newer' },
  '0.50': { showVersion: 5, stepMode: 'time', label: 'MPF 0.50 - 0.56 (legacy)' },
};

function hex2(v) {
  return Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, '0').toUpperCase();
}

function needsQuotes(name) {
  return !/^[A-Za-z_][A-Za-z0-9_]*$/.test(name);
}

function allBlack(frame) {
  for (let i = 0; i < frame.length; i++) if (frame[i] !== 0) return false;
  return true;
}

/**
 * Render every frame and emit the show.
 *
 * @param project    the show being exported
 * @param lights     [{name,x,y,...}]
 * @param renderer   ShowRenderer
 * @param onProgress optional (done, total) => void
 */
export async function buildShow(project, lights, renderer, onProgress) {
  const opts = project.export || {};
  const fps = project.fps || 30;
  const total = frameCount(project);
  const durationMs = projectDuration(project);
  const stepMs = 1000 / fps;
  const diffOnly = opts.diffOnly !== false;
  const idleMode = opts.idleMode || 'hold';
  const dialect = MPF_TARGETS[opts.mpfTarget] || MPF_TARGETS['0.80'];

  // ---- pass 1: render and sample everything -------------------------------
  const frames = [];
  for (let f = 0; f < total; f++) {
    // exactly the call the preview uses, so the two cannot drift apart
    frames.push(new Uint8ClampedArray(renderer.render(project, lights, f * stepMs, opts)));
    if (onProgress) onProgress(f + 1, total);
    if (f % 20 === 19) await new Promise((r) => setTimeout(r, 0));
  }

  // ---- trim dead frames at the head and tail ------------------------------
  // Trimming the head shifts every cue earlier, which silently desynchronises a
  // show cut to video, so it is off unless explicitly asked for.
  let first = 0;
  let last = total - 1;
  const trimStart = opts.trimStart === true;
  const trimEnd = opts.trimEnd !== false;
  if (trimStart) while (first <= last && allBlack(frames[first])) first++;
  if (trimEnd) while (last >= first && allBlack(frames[last])) last--;
  const trimmedFrames = last >= first ? last - first + 1 : 0;

  const lines = [];
  const push = (s) => lines.push(s);

  // MPF compares this line for equality - it must come first and match exactly.
  push(`#show_version=${dialect.showVersion}`);
  push(`# ${project.name}`);
  push(`# generated by Claude Show Creator - ${trimmedFrames} frames @ ${fps} fps `
     + `(${(trimmedFrames * stepMs / 1000).toFixed(2)}s)`);
  if (dialect.stepMode === 'duration') {
    push('# step durations are explicit, so play this show at the default speed');
  } else {
    push(`# legacy timing: each step is "+1", so play this show with speed: ${fps}`);
  }

  if (trimmedFrames === 0) {
    push('# nothing is lit anywhere in this show');
    return {
      yaml: lines.join('\n') + '\n',
      stats: emptyStats(total, first, durationMs, fps, dialect),
    };
  }

  // ---- pass 2: diff frames into steps -------------------------------------
  // A step is a set of light changes plus how many frames it stays on screen.
  const prev = new Int16Array(lights.length * 3).fill(-1);
  const touched = new Set();
  const steps = [];
  let idleFrames = 0;
  let lastEntries = [];

  for (let f = first; f <= last; f++) {
    const colors = frames[f];
    const entries = [];
    for (let i = 0; i < lights.length; i++) {
      const r = colors[i * 3], g = colors[i * 3 + 1], b = colors[i * 3 + 2];
      const changed = prev[i * 3] !== r || prev[i * 3 + 1] !== g || prev[i * 3 + 2] !== b;
      prev[i * 3] = r; prev[i * 3 + 1] = g; prev[i * 3 + 2] = b;
      if (diffOnly && !changed) continue;
      if (diffOnly && !steps.length && r === 0 && g === 0 && b === 0) continue;
      entries.push({ name: lights[i].name, r, g, b });
      touched.add(lights[i].name);
    }

    if (entries.length) {
      steps.push({ entries, frames: 1 });
      lastEntries = entries;
      continue;
    }

    idleFrames++;
    if (idleMode === 'collapse') {
      // nothing changed, so simply hold what is on screen for longer. With no
      // step yet there is nothing to extend, so open an empty one to hold time.
      if (steps.length) steps[steps.length - 1].frames++;
      else steps.push({ entries: [], frames: 1 });
    } else if (idleMode === 'hold' && lastEntries.length) {
      steps.push({ entries: lastEntries, frames: 1, restated: true });
    } else {
      steps.push({ entries: [], frames: 1 });
    }
  }

  // ---- pass 3: write ------------------------------------------------------
  const writeEntries = (entries) => {
    if (!entries.length) return;
    push('  lights:');
    for (const e of entries) {
      const name = needsQuotes(e.name) ? `'${e.name}'` : e.name;
      const off = e.r === 0 && e.g === 0 && e.b === 0;
      if (off && opts.blackAsStop) {
        push(`    ${name}: stop`);
      } else if (opts.fadeMs > 0) {
        push(`    ${name}:`);
        push(`      color: '${hex2(e.r)}${hex2(e.g)}${hex2(e.b)}'`);
        push(`      fade: ${Math.round(opts.fadeMs)}ms`);
      } else {
        push(`    ${name}: '${hex2(e.r)}${hex2(e.g)}${hex2(e.b)}'`);
      }
    }
  };

  let frameCursor = 0;
  steps.forEach((step, i) => {
    if (dialect.stepMode === 'duration') {
      // Derive each duration from the cumulative timeline so rounding cannot
      // drift: 30fps gives 33/33/34ms rather than 33ms every step.
      const startMs = Math.round(frameCursor * stepMs);
      const endMs = Math.round((frameCursor + step.frames) * stepMs);
      push(`- duration: ${Math.max(1, endMs - startMs)}ms`);
    } else if (i === 0) {
      push('- time: 0');
    } else {
      push(`- time: '+${steps[i - 1].frames}'`);
    }
    frameCursor += step.frames;

    // An idle step is the duration alone. Emitting a `lights:` key with nothing
    // under it parses as `lights: null`, which MPF rejects outright with
    // "Invalid settings for player ...:lights None".
    if (step.entries.length) writeEntries(step.entries);
  });

  // Guard the invariant rather than trusting the writer above: a `lights:` with
  // no entry beneath it would break the machine, so never hand one back.
  for (let i = 0; i < lines.length; i++) {
    if (/^\s+lights:\s*$/.test(lines[i]) && !/^ {4}\S/.test(lines[i + 1] || '')) {
      throw new Error(`internal error: empty lights block at output line ${i + 1}. `
        + 'The show was not written.');
    }
  }

  return {
    yaml: lines.join('\n') + '\n',
    stats: {
      frames: trimmedFrames,
      sourceFrames: total,
      steps: steps.length,
      changedFrames: steps.filter((s) => s.entries.length && !s.restated).length,
      idleFrames,
      trimmedHead: first,
      trimmedTail: total - 1 - last,
      headShiftMs: Math.round(first * stepMs),
      lightsTouched: touched.size,
      totalLights: lights.length,
      durationMs,
      fps,
      showVersion: dialect.showVersion,
      stepMode: dialect.stepMode,
    },
  };
}

function emptyStats(total, first, durationMs, fps, dialect) {
  return {
    frames: 0, sourceFrames: total, steps: 0, changedFrames: 0, idleFrames: 0,
    trimmedHead: first, trimmedTail: 0, lightsTouched: 0, totalLights: 0,
    durationMs, fps, showVersion: dialect.showVersion, stepMode: dialect.stepMode,
  };
}

/** Suggest a filename from the show name. */
export function suggestFilename(name) {
  const base = String(name || 'show')
    .trim()
    .replace(/[^A-Za-z0-9 _.-]/g, '')
    .replace(/\s+/g, '_')
    .slice(0, 60) || 'show';
  return base + '.yaml';
}
